### PR TITLE
Add KEDA dashboard

### PR DESCRIPTION
**Pull request by shrutimantri**
Sample KEDA dashboard: https://svey-5nsw.in.signoz.cloud/dashboard/0e6f69f2-d987-498b-b351-ba2b62a902ba?relativeTime=3d

### CODE REVIEW

**Comment by rajeshj11** [comment]
@shrutimantri Could you clarify how you're obtaining the metrics data without running KEDA-related services? I assumed you're running a KEDA Docker image locally, but if that's not the case, could you explain how you're retrieving the metrics?

**Comment by shrutimantri** [comment]
I do not see the above comment in PR any more.
But to clarify, yes, I was running k8s cluster locally, and tested KEDA by
locally adding scaling factors for the service.

Regards,
Shruti

**Review by makeavish — APPROVED** [review]
Build version is missing as it's not supported by query builder currently. To be added later.

**Comment by srikanthccv** [comment]
Why did you use `time_series_v2` tables for variables?

**Comment by srikanthccv** [comment]
We worked on removing them from all existing dashboards. I want to understand where did you come across v2 and why did you use v2 when all the existing dashboards use v4.

**Pull request merged**
